# ~/.config/starship.toml

[cmd_duration]
min_time = 200
show_milliseconds=true
format = 'took [$duration](bold yellow)'


[kubernetes]
disabled = false


[python]
disabled = false
symbol = " "

[golang]
disabled = false
symbol = " "
