# ~/.config/starship.toml

# Moved kubernetes near aws and gcloud
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$kubernetes\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""


[cmd_duration]
min_time = 200
show_milliseconds=true
format = 'took [$duration](bold yellow)'


[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '


[python]
disabled = false
symbol = " "


[golang]
disabled = false
symbol = " "


# AWS Configuration
[aws]
format = '[$symbol($profile )(\($region\) )]($style)'
symbol = "󰸏 " # AWS symbol
style = "bold yellow"
disabled = false


[aws.region_aliases]
us-east-1 = "ue1"
us-west-2 = "uw2"
ap-northeast-1 = "apne1"


# Google Cloud Configuration
[gcloud]
format = '[$symbol$account(@$domain)(\($project\))]($style) '
symbol = "󰊭 " # Google Cloud symbol
style = "bold blue"
disabled = true


[directory]
truncation_length = 3
style = "bold cyan"


[git_branch]
symbol = "󰊢 "

